apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gohttpserver
  labels:
    name: gohttpserver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - "go.todoit.tech"
      secretName: wildcard-letsencrypt-tls
  rules:
    - host: go.todoit.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gohttpserver
                port:
                  number: 8080
